---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/Shared/workspace/MCA2/ds/lab3Stack/stack'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _getPrecedence, symObjAddr: 0x0, symBinAddr: 0x100003A84, symSize: 0xA8 }
  - { offsetInCU: 0x41, offset: 0x41, size: 0x8, addend: 0x0, symName: _getPrecedence, symObjAddr: 0x0, symBinAddr: 0x100003A84, symSize: 0xA8 }
  - { offsetInCU: 0x69, offset: 0x69, size: 0x8, addend: 0x0, symName: _infixToPostfix, symObjAddr: 0xA8, symBinAddr: 0x100003B2C, symSize: 0x364 }
  - { offsetInCU: 0xEF, offset: 0xEF, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x40C, symBinAddr: 0x100003E90, symSize: 0xAC }
...
